name: Build and Push Docker Image

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Checkout the code
    - uses: actions/checkout@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build, tag, and push image to Docker Hub
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        IMAGE_NAME: midas-dcm4chee-psql-cli
        COMMIT_SHA: ${{ github.sha }}
      run: |
        IMAGE_TAG=${COMMIT_SHA::7}
        docker build -t $DOCKER_HUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG -t $DOCKER_HUB_USERNAME/$IMAGE_NAME:latest .
        docker push $DOCKER_HUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG
        docker push $DOCKER_HUB_USERNAME/$IMAGE_NAME:latest